services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: LTAIsupersecretkeyfordat
      POSTGRES_USER: owasp10
      POSTGRES_DB: owasp10
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    restart: unless-stopped
  owasp10:
    build: .
    ports:
      - 8090:80
    environment:
      FLASK_DEBUG: "1"
